apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: front
spec:
  selector:
    app: front
    type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080 #service
      targetPort: 80 #pod