apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: cpu-demo
    image: vish/stress
    #command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
    resources:
      limits:
        cpu: "1000m"
      requests: 
        cpu: "500m"
    args:
    - -cpus
    - "2"