apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: memory-demo
    image: polinux/stress
    #command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
    resources:
      limits:
        memory: "200Mi"
      requests: 
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]