apiVersion: batch/v1
kind: Job
metadata:
  name: pods1
  labels:
    app: front
    env: dev
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: cont1
        image: nginx
        #command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: OnFailure
    # The pod template ends here
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pods2
  labels:
    app: back
    env: dev
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: cont1
        image: nginx
        #command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: OnFailure
    # The pod template ends here