apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  namespace: dev
  labels:
    app: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: ricardoandre97/backend-k8s-hands-on:v2
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: service-back
  namespace: dev
  labels:
    app: back
spec:
  type: NodePort
  selector:
    app: back
  ports:
    - protocol: TCP
      port: 80 #service
      targetPort: 9090 #pod
      nodePort: 30080